name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'
   
    - name: Format
      uses: Jerome1337/gofmt-action@v1.0.5
      with:
        gofmt-flags: '-l -d'

    - name: Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

    - name: Build
      run: make

    - name: Test
      run: make test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
